version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/watertrack
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=alterar123
      - FIREBASE_CONFIG=${FIREBASE_CONFIG}  # Será injetado via .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=watertrack
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha_segura
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: